# Exercises on pandas Basics

## 1. Getting Started
We first import `pandas` and load a table into a DataFrame.

In [2]:
import pandas as pd

countries = pd.read_csv('../data/Large_Countries/large_countries_2015.csv', 
                        index_col=0)

type(countries["population"])
countries.dtypes

FileNotFoundError: [Errno 2] No such file or directory: '../data/Large_Countries/large_countries_2015.csv'

## 2. Working with DataFrames

To view the contents of a data frame, type its name:

In [ ]:
countries

                 population  fertility      continent
Bangladesh     1.609956e+08       2.12           Asia
Brazil         2.078475e+08       1.78  South America
China          1.376049e+09       1.57           Asia
India          1.311051e+09       2.43           Asia
Indonesia      2.575638e+08       2.28           Asia
Japan          1.265735e+08       1.45           Asia
Mexico         1.270172e+08       2.13  North America
Nigeria        1.822020e+08       5.89         Africa
Pakistan       1.889249e+08       3.04           Asia
Philippines    1.006994e+08       2.98           Asia
Russia         1.434569e+08       1.61         Europe
United States  3.217736e+08       1.97  North America

## 3. Examining DataFrames
Match the Python commands with the descriptions below. 

*In Jupyter, you can move the descriptions up/down with the arrow buttons.*

In [ ]:
countries.head(3)

              population  fertility      continent
Bangladesh  1.609956e+08       2.12           Asia
Brazil      2.078475e+08       1.78  South America
China       1.376049e+09       1.57           Asia

In [ ]:
countries.tail(3)

                population  fertility      continent
Philippines    100699395.0       2.98           Asia
Russia         143456918.0       1.61         Europe
United States  321773631.0       1.97  North America

In [ ]:
countries.describe()

         population  fertility
count  1.200000e+01  12.000000
mean   3.753462e+08   2.437500
std    4.565194e+08   1.200781
min    1.006994e+08   1.450000
25%    1.393470e+08   1.737500
50%    1.855634e+08   2.125000
75%    2.736163e+08   2.567500
max    1.376049e+09   5.890000

In [ ]:
countries['population'].mean()

375346161.6666667

In [ ]:
countries['continent'].value_counts()

Asia             7
North America    2
Africa           1
Europe           1
South America    1
Name: continent, dtype: int64

In [ ]:
countries.shape

(12, 3)

In [ ]:
countries['continent']

Bangladesh                Asia
Brazil           South America
China                     Asia
India                     Asia
Indonesia                 Asia
Japan                     Asia
Mexico           North America
Nigeria                 Africa
Pakistan                  Asia
Philippines               Asia
Russia                  Europe
United States    North America
Name: continent, dtype: object

In [ ]:
countries['continent'].unique()

array(['Asia', 'South America', 'North America', 'Africa', 'Europe'],
      dtype=object)

In [ ]:
countries['population'] // 1000000

Bangladesh        160.0
Brazil            207.0
China            1376.0
India            1311.0
Indonesia         257.0
Japan             126.0
Mexico            127.0
Nigeria           182.0
Pakistan          188.0
Philippines       100.0
Russia            143.0
United States     321.0
Name: population, dtype: float64

#### Number of rows and columns

#### Show the last 3 lines

#### Summarize categorical data

#### Mean of a column

#### Summarize all numerical columns

#### Show the first 3 lines

#### Apply a calculation to each value in a column

#### Extract distinct values

## 4. Selecting rows and columns
Match the Python commands with the descriptions below.

In [ ]:
countries.columns

In [ ]:
countries.index

In [ ]:
type(countries['continent'])

In [ ]:
countries[['population', 'continent']]
#countries.loc[['Brazil','China']]

In [ ]:
countries.loc['India']

In [ ]:
countries.iloc[3:7]

In [ ]:
countries[countries['population'] > 200000000]

In [ ]:
countries.values

#### Extract raw data as a NumPy array

#### Select rows by slicing the index

#### Filter rows by a condition

#### Display column labels

#### Select multiple columns

#### Display row index

#### Select row by an index value

#### Select one column

## 5. Summarizing Data
Match the Python commands with the descriptions below.

In [ ]:
countries['fertility'].cumsum()

In [ ]:
countries.groupby('continent')['population'].sum()

In [ ]:
countries.sort_values(by=['continent', 'fertility'], ascending=[False,True])

In [ ]:
def get_initial(s):
    return s[0]

countries['initial'] = countries['continent'].apply(get_initial)
countries

In [ ]:
countries.stack()

In [ ]:
countries.transpose()

In [ ]:
countries['fertility'].hist(bins=2)

In [ ]:
countries.plot('population', 'fertility', style='ro')

#### Draw a scatterplot

#### Move columns to a new index level

#### Create a new column using a function

#### Draw a histogram

#### Cumulatively apply a sum over a column

#### Swap rows and columns

#### Calculate sum of one column grouped by a second one

#### Sort values

## License
(c) 2017 Kristian Rother
Distributed under the conditions of the MIT License.